services:
  - type: web
    name: rare-pick
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: DATABASE_URL
        sync: false
